/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-07 08:38:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.customerservice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.semi01.notice.model.vo.Notice;
import java.util.ArrayList;
import com.kh.semi01.user.model.vo.Review;
import java.util.ArrayList;
import com.kh.semi01.common.model.vo.PageInfo;
import com.kh.semi01.product.model.vo.Product;
import java.util.ArrayList;
import com.kh.semi01.user.model.vo.User;

public final class noticeList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/customerservice/../common/header.jsp", Long.valueOf(1694057600000L));
    _jspx_dependants.put("/views/customerservice/../common/footer.jsp", Long.valueOf(1694057600000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.semi01.user.model.vo.Review");
    _jspx_imports_classes.add("com.kh.semi01.common.model.vo.PageInfo");
    _jspx_imports_classes.add("com.kh.semi01.notice.model.vo.Notice");
    _jspx_imports_classes.add("com.kh.semi01.user.model.vo.User");
    _jspx_imports_classes.add("com.kh.semi01.product.model.vo.Product");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

	ArrayList<Notice> list = (ArrayList<Notice>)request.getAttribute("list");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style>\n");
      out.write("/* 바디 시작 */\n");
      out.write("               /* 바디 메인 */\n");
      out.write("               .원하는데로_바꾸세요{\n");
      out.write("                border: 1px solid lightgray; \n");
      out.write("           background-color: #f8f9fa; \n");
      out.write("            height: 900px;\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* body 고객센터*/\n");
      out.write("        .servicecenter{\n");
      out.write("            \n");
      out.write("            background-color:black;\n");
      out.write("            height: 100px;\n");
      out.write("            width: 1050px;\n");
      out.write("            margin:auto;\n");
      out.write("            margin-right: 23.8%;\n");
      out.write("            margin-top:50px;            \n");
      out.write("        }\n");
      out.write("        .servicecenter>h1{\n");
      out.write("            color:white;\n");
      out.write("            line-height:100px;\n");
      out.write("        } \n");
      out.write("\n");
      out.write("        /*body leftmenu*/\n");
      out.write("        .원하는데로_바꾸세요 .leftmenu{\n");
      out.write("            background-color: white;\n");
      out.write("            font-size: 19px;\n");
      out.write("            text-align:center;\n");
      out.write("            line-height: 100px;\n");
      out.write("            width: 160px;\n");
      out.write("            height: 300px;\n");
      out.write("            margin-left: 21%;\n");
      out.write("            margin-top: 5px;\n");
      out.write("            float:left;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .원하는데로_바꾸세요 .leftmenu div{\n");
      out.write("            width:100%;\n");
      out.write("            height: 99.3px;\n");
      out.write("            border: 0.3px solid gray;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .원하는데로_바꾸세요>.white{\n");
      out.write("        width:100%;\n");
      out.write("        height:0px;\n");
      out.write("        border: 1px solid gray;\n");
      out.write("        }\n");
      out.write("        #announce>p{\n");
      out.write("            display: none;\n");
      out.write("            float:right;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /*바디의 오른쪽 메뉴*/\n");
      out.write("        .원하는데로_바꾸세요 .rightmenu{\n");
      out.write("            background-color: white;\n");
      out.write("            width: 880px;\n");
      out.write("            height:600px;\n");
      out.write("            margin-right: 23.8%;\n");
      out.write("            margin-top: 5px;\n");
      out.write("            float:right;\n");
      out.write("        }\n");
      out.write("        .rightmain{\n");
      out.write("            width:100%\n");
      out.write("        }\n");
      out.write("        #event{\n");
      out.write("            width: 100%;\n");
      out.write("            height: 150px;\n");
      out.write("            /* border:  2px solid red; */\n");
      out.write("            /* margin-top: 10px; */\n");
      out.write("            border: 0;\n");
      out.write("            background-color: white;\n");
      out.write("        }\n");
      out.write("        .rightmain tbody>tr:hover{\n");
      out.write("        background:gray;\n");
      out.write("        cursor:pointer;\n");
      out.write("    	opacity:0.5;\n");
      out.write("        }\n");
      out.write("        .rightmain th{\n");
      out.write("            height:40px;\n");
      out.write("        }\n");
      out.write("        /*테이블 첫 번째 줄*/\n");
      out.write("        #tr1{\n");
      out.write("            background-color: lightblue;\n");
      out.write("            font-size: 20px;\n");
      out.write("            text-align: center;\n");
      out.write("            color:gray\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* 바디 끝 */\n");
      out.write("        /* 푸터 시작 */\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String contextPath = request.getContextPath();

	User loginMember = (User)session.getAttribute("loginMember");
	
	String alertMsg = (String)session.getAttribute("alertMsg");


      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>티켓딱대</title>\n");
      out.write("<link href=\"resource/logo/symbol.png\" rel=\"shortcut icon\" type=\"image/x-icon\">\n");
      out.write("<!-- jQuery library -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\n");
      out.write("<style>\n");
      out.write("    /* 기본 세팅 존 */\n");
      out.write("\n");
      out.write("    /* 모든 마진 패딩 지우 */\n");
      out.write("    body, div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, p, table, th, td, form, fieldset, legend, textarea, input, select, textarea, button, article, aside, dialog, footer, header, section, footer, nav, figure, main {\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    } \n");
      out.write("\n");
      out.write("    /* 폰트 옵션 */\n");
      out.write("    body, input, select, textarea, button, pre {\n");
      out.write("    font-family: 'Notosans', -apple-system, BlinkMacSystemFont, Apple SD Gothic Neo, 'Malgun Gothic', Arial, sans-serif;\n");
      out.write("    font-size: 14px;\n");
      out.write("    letter-spacing: -0.03em;\n");
      out.write("    color: #242428;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    a{\n");
      out.write("        text-decoration: none;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 기본세팅 끝 */\n");
      out.write("\n");
      out.write("    /* 헤더 */\n");
      out.write("\n");
      out.write("    /* 배경 옵션*/\n");
      out.write("    .warp{\n");
      out.write("        /* border: 1px solid plum; */\n");
      out.write("        display: flex;\n");
      out.write("        flex-direction: column;\n");
      out.write("        position: relative;\n");
      out.write("        min-width: 1180px;\n");
      out.write("        min-height: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    /* 유틸란 */\n");
      out.write("    .util {\n");
      out.write("        flex-direction: column;\n");
      out.write("        position: relative;\n");
      out.write("        min-width: 1180px;\n");
      out.write("        margin: 0 auto;\n");
      out.write("        width: 100%;\n");
      out.write("        height: 37px;\n");
      out.write("    \n");
      out.write("        /* background-color: rgb(241, 241, 241); */\n");
      out.write("        background-color: #f8f8f8;\n");
      out.write("        }\n");
      out.write("           \n");
      out.write("    .util_inner{ /* 배경색 주기위한 디브*/\n");
      out.write("        /* border: 1px solid yellow; */\n");
      out.write("       \n");
      out.write("        /* margin: auto; */\n");
      out.write("        width: 1120px;\n");
      out.write("        height: 37px;\n");
      out.write("        margin-left: 450px;\n");
      out.write("    }\n");
      out.write("    /* 유틸난 나누는 디브 */\n");
      out.write("    .util_inner>div{\n");
      out.write("        /* border: 1px solid blue; */\n");
      out.write("        height: 37px;\n");
      out.write("        box-sizing: border-box;\n");
      out.write("        float: left;\n");
      out.write("    }\n");
      out.write("    .left{\n");
      out.write("        width: 50%;\n");
      out.write("    }\n");
      out.write("    .right{\n");
      out.write("        width: 50%;\n");
      out.write("    }\n");
      out.write("    /* 오른쪽 내용물 */\n");
      out.write("    .right>div{\n");
      out.write("        /* border: 1px solid blue; */\n");
      out.write("        height: 100%;\n");
      out.write("        float: left;\n");
      out.write("        box-sizing: border-box;\n");
      out.write("        width: 20%;\n");
      out.write("    }\n");
      out.write("    .login,.sin,.contact,.user_info{\n");
      out.write("        width: 20%;\n");
      out.write("        box-sizing: border-box;\n");
      out.write("    }\n");
      out.write("    .check{\n");
      out.write("        width: 29.5%;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 유틸란 링크 사이즈 */\n");
      out.write("    .header_util_link {\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center; /* Center vertically */\n");
      out.write("    justify-content: center; /* Center horizontally */\n");
      out.write("    margin-top: 8px;\n");
      out.write("    font-size: 15px;\n");
      out.write("    line-height: 18px;\n");
      out.write("    color: #878d95;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 유틸 끝 */\n");
      out.write("\n");
      out.write("    /* 메인 시작 */\n");
      out.write("    .header_main {\n");
      out.write("    /* border: 1px solid ; */\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    margin: 0 auto;\n");
      out.write("    width: 1120px;\n");
      out.write("    height: 88px;\n");
      out.write("    margin-left: 360px;\n");
      out.write("    }\n");
      out.write("    .header_main>div{\n");
      out.write("        /* border: 1px solid yellowgreen; */\n");
      out.write("        height: 100%;\n");
      out.write("    }\n");
      out.write("    .header_main_left{\n");
      out.write("        width: 13%;\n");
      out.write("    }\n");
      out.write("    .header_main_mid{\n");
      out.write("        width: 67%;\n");
      out.write("    }\n");
      out.write("    .header_main_right{\n");
      out.write("        width: 20%;\n");
      out.write("    }\n");
      out.write("    /* 메인 미드 로고 */\n");
      out.write("    #logo_main{\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("    }\n");
      out.write("    /* 메인 미드  케테고리 */\n");
      out.write("    .header_nav_link {\n");
      out.write("    /* border: 1px solid; */\n");
      out.write("    width: 30%;\n");
      out.write("    font-size: 30px;\n");
      out.write("    font-weight: 700;\n");
      out.write("    line-height: 34px;\n");
      out.write("    letter-spacing: -0.04em;\n");
      out.write("    color: #242428;\n");
      out.write("    margin-left: 25px;\n");
      out.write("    margin-top:  35px; \n");
      out.write("    float: left;       \n");
      out.write("    }\n");
      out.write("    /* 메인 미드 끝 */\n");
      out.write("\n");
      out.write("    /* 네비게이터 */\n");
      out.write("\n");
      out.write("    .header_gnb { /* 내비게이터 배경 */\n");
      out.write("    /* border: 1px solid blue; */\n");
      out.write("    position: relative;\n");
      out.write("    border-top: 1px solid #ecedf2;\n");
      out.write("    border-bottom: 1px solid #f8f8f8;\n");
      out.write("    width: 100%;\n");
      out.write("    height: 58px;\n");
      out.write("    margin: auto;\n");
      out.write("    }\n");
      out.write("    #navigator{\n");
      out.write("        width: 1200px;\n");
      out.write("        height: 40px; \n");
      out.write("        margin: auto;\n");
      out.write("        padding-top: 10px;\n");
      out.write("        margin-left: 350px;\n");
      out.write("        /* border: 1px solid red; */\n");
      out.write("    }\n");
      out.write("    #navi{\n");
      out.write("        list-style-type: none;\n");
      out.write("        padding: 0;\n");
      out.write("        margin: 0;\n");
      out.write("        height: 100%;\n");
      out.write("        width: 75%;\n");
      out.write("        /* border: 1px solid blue; */\n");
      out.write("        float: left;\n");
      out.write("        box-sizing: border-box;\n");
      out.write("    }\n");
      out.write("    #navi>li{\n");
      out.write("        float: left;\n");
      out.write("        /* border: 1px solid blue; */\n");
      out.write("        width: 8%;\n");
      out.write("        height: 100%;\n");
      out.write("        text-align: center;\n");
      out.write("    }\n");
      out.write("    #navi a{\n");
      out.write("        /* border: 1px solid orange; */\n");
      out.write("        text-decoration: none;\n");
      out.write("        /* color: orange; */\n");
      out.write("        font-size: 18px;\n");
      out.write("        font-weight: 900;\n");
      out.write("        width: 100%;\n");
      out.write("        height: 47px;\n");
      out.write("        display: block;\n");
      out.write("        line-height: 35px;\n");
      out.write("        transform: scale(1);\n");
      out.write("    }\n");
      out.write("    #navi a:hover{\n");
      out.write("        color: orangered;\n");
      out.write("    }\n");
      out.write("    #navi>li>ul{\n");
      out.write("        list-style-type: none;\n");
      out.write("        padding: 0;\n");
      out.write("        display: none;\n");
      out.write("        border: 1px solid;\n");
      out.write("        width: 150%;\n");
      out.write("        margin-left: -16px;\n");
      out.write("    }\n");
      out.write("    #navi>li>ul a{font-size: 18px;}\n");
      out.write("    #navi>li>a:hover+ul{display: block;}\n");
      out.write("    #navi>li>ul:hover{display: block;}\n");
      out.write("    #navi>li>ul>li{\n");
      out.write("        background-color: white;\n");
      out.write("    }\n");
      out.write("    /* 네비 끝 */\n");
      out.write("\n");
      out.write("    /* 검색 시작 */\n");
      out.write("    \n");
      out.write("    .header_search_box {\n");
      out.write("        /* border: 1px solid green; */\n");
      out.write("        width: 25%;\n");
      out.write("        height: 100%;\n");
      out.write("        float: left;\n");
      out.write("        box-sizing: border-box;\n");
      out.write("    }\n");
      out.write("    .header_search_input {\n");
      out.write("    width: 240px;\n");
      out.write("    padding: 7px 55px 7px 18px;\n");
      out.write("    border: 1px solid #dcdde1;\n");
      out.write("    border-radius: 38px;\n");
      out.write("    background: #fff;\n");
      out.write("    font-size: 14px;\n");
      out.write("    line-height: 22px;\n");
      out.write("    color: #242428;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    outline: none;\n");
      out.write("    caret-color: #fa2828;\n");
      out.write("    float: left;\n");
      out.write("    }\n");
      out.write("    #btnImg{\n");
      out.write("        width: 35px;\n");
      out.write("        height: 35px;\n");
      out.write("        /* border:  2px solid red; */\n");
      out.write("        /* margin-top: 10px; */\n");
      out.write("        border: 0;\n");
      out.write("        background-color: white;\n");
      out.write("        margin-left: 10px;\n");
      out.write("    }\n");
      out.write("    #btn_Img{\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .header_gnb{\n");
      out.write("        position: relative;\n");
      out.write("        z-index: 2;\n");
      out.write("    }\n");
      out.write("    .main_category[main-selected=\"true\"]{\n");
      out.write("        color: red;\n");
      out.write("    }\n");
      out.write("    .main_category[main-selected=\"false\"]{\n");
      out.write("        color: black;\n");
      out.write("    }\n");
      out.write("    .minCategory{\n");
      out.write("        color: black;\n");
      out.write("    }\n");
      out.write("    /* 검색 끝 */\n");
      out.write("    /* 헤더 끝 */\n");
      out.write("    /* 작은카테고리 앞으로 나오게*/\n");
      out.write("    \n");
      out.write("\n");
      out.write("    \n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	\n");
      out.write("	");
 if(alertMsg != null) { 
      out.write("\n");
      out.write("	\n");
      out.write("		<script>\n");
      out.write("			alert(\"");
      out.print( alertMsg );
      out.write("\");\n");
      out.write("		</script>\n");
      out.write("		\n");
      out.write("		");
 session.removeAttribute("alertMsg"); 
      out.write("\n");
      out.write("		\n");
      out.write("	");
 } 
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"warp\"> <!-- 기본 배경-->\n");
      out.write("\n");
      out.write("        <div class=\"header\"> <!-- 헤더-->\n");
      out.write("\n");
      out.write("            <div class=\"util\"> <!-- 유틸 부분 (로긴..)-->\n");
      out.write("                <div class=\"util_inner\">\n");
      out.write("                    <div class=\"left\"></div>\n");
      out.write("                    \n");
      out.write("                    <!-- 로그인 전 화면  --> \n");
      out.write("                    ");
 if(loginMember == null){ 
      out.write("\n");
      out.write("                     <div class=\"right\" >\n");
      out.write("						<div class=\"user_info\">\n");
      out.write("                            <a href=\"#\" class=\"header_util_link\" ></a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"login\">\n");
      out.write("                            <a href=\"");
      out.print(contextPath );
      out.write("/login.ur\" class=\"header_util_link\" >로그인</a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"check\">\n");
      out.write("                            <a href=\"#\" class=\"header_util_link\" onclick=\"book();\">예매확인/취소</a>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <script>\n");
      out.write("\n");
      out.write("                            function book() {\n");
      out.write("                                \n");
      out.write("                                if(confirm(\"로그인 후에 이용 가능한 서비스입니다. 로그인 하시겠습니까?\")) {\n");
      out.write("                                	\n");
      out.write("                                	location.href = \"/semi01/login.ur\"\n");
      out.write("                                	\n");
      out.write("                                }\n");
      out.write("                                \n");
      out.write("                                return false;\n");
      out.write("\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                        </script>\n");
      out.write("\n");
      out.write("                        <div class=\"sin\">\n");
      out.write("                            <a href=\"");
      out.print(contextPath );
      out.write("/newUser.ur\" class=\"header_util_link\">회원가입</a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"contact\">\n");
      out.write("                            <a href=\"");
      out.print(contextPath );
      out.write("/customer.cu\" class=\"header_util_link\">고객센터</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div> \n");
      out.write("                    ");
}else { 
      out.write("\n");
      out.write("	\n");
      out.write("                    <!-- 로그인 후 화면 -->\n");
      out.write("                     <div class=\"right\" >\n");
      out.write("						<div class=\"user_info\">\n");
      out.write("							");
 if(loginMember.getUserNo() == 1){ 
      out.write("\n");
      out.write("								<div  class=\"header_util_link\" style=\"font-weight: 900; color: #242428;\" ><a href=\"/manager-member.do?cpage=1\">관리자페이지</a></div>\n");
      out.write("							");
}else { 
      out.write("\n");
      out.write("                            <div  class=\"header_util_link\" style=\"font-weight: 900; color: #242428;\" >");
      out.print(loginMember.getUserName() );
      out.write(" 님</div>\n");
      out.write("							");
} 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"login\">\n");
      out.write("                            <a href=\"");
      out.print(contextPath );
      out.write("/logout.me\" class=\"header_util_link\" >로그아웃</a>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"check\">\n");
      out.write("                            <a href=\"");
      out.print( contextPath );
      out.write("/myTicket.us?cpage=1\" class=\"header_util_link\">예매확인/취소</a>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"sin\">\n");
      out.write("                            <a href=\"");
      out.print( contextPath );
      out.write("/myPage.us\" class=\"header_util_link\">마이페이지</a>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"contact\">\n");
      out.write("                            <a href=\"");
      out.print(contextPath );
      out.write("/customer.cu\" class=\"header_util_link\">고객센터</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div> \n");
      out.write("                    ");
} 
      out.write("\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"header_main\"> <!-- 헤더 메인 (로고, 대카테고리)-->\n");
      out.write("                <div class=\"header_main_left\"> <!-- 로고-->\n");
      out.write("                    <a href=\"");
      out.print( contextPath );
      out.write("\" class=\"logo\"><img src=\"resource/logo/logo.png\" id=\"logo_main\"></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"header_main_mid\"> <!-- 대카테고리-->\n");
      out.write("                    <a href=\"#\" class=\"category\"  >\n");
      out.write("                        <p  class=\"header_nav_link\" >영화/전시/공연</p></a>\n");
      out.write("                    <a href=\"#\" class=\"category\" onclick=\"not();\">\n");
      out.write("                        <p class=\"header_nav_link\"  style=\"width: 10%; color: #979797;\" >항공</p>\n");
      out.write("                        <p class=\"header_nav_link\" style=\" color: #979797;\">스포츠</p></a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <script>\n");
      out.write("                    function not() {\n");
      out.write("                        alert(\"준비중입니다.\")\n");
      out.write("                    }\n");
      out.write("                </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"header_main_right\"></div> <!-- 로고공백 -->\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"header_gnb\">  <!-- 해더 네비게이터 -->\n");
      out.write("                <div id=\"navigator\"> <!-- 네비게이터 기본 틀-->\n");
      out.write("                    <ul id=\"navi\" > <!-- 카테고리-->\n");
      out.write("                        <li><a href=\"");
      out.print( contextPath );
      out.write("\" class=\"main_category\" id=\"홈\" main-selected=\"true\" >홈</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li><a href=\"");
      out.print( contextPath );
      out.write("/cmain.pr?ctype=영화\" class=\"main_category\" id=\"영화\" main-selected=\"false\">영화</a>\n");
      out.write("                            <ul>\n");
      out.write("                                <li aligh=\"center\"><a href=\"");
      out.print( contextPath );
      out.write("/rmovie.pr?ctype=로맨스\" class=\"minCategory\">로맨스</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/rmovie.pr?ctype=공포스릴러\" class=\"minCategory\">공포/스릴러</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/rmovie.pr?ctype=코미디\" class=\"minCategory\">코미디</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/rmovie.pr?ctype=액션\" class=\"minCategory\">액션</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        \n");
      out.write("                        </li>\n");
      out.write("                        <li><a href=\"");
      out.print( contextPath );
      out.write("/cmain.pr?ctype=전시\" class=\"main_category\" id=\"전시\" main-selected=\"false\" >전시</a>\n");
      out.write("                            <ul>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/rmovie.pr?ctype=그림전시\" class=\"minCategory\">그림전시</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/rmovie.pr?ctype=작품전시\" class=\"minCategory\">작품전시</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/rmovie.pr?ctype=사진전시\" class=\"minCategory\">사진전시</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/rmovie.pr?ctype=체험전시\" class=\"minCategory\">체험전시</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li><a href=\"");
      out.print( contextPath );
      out.write("/cmain.pr?ctype=공연\" class=\"main_category\" id=\"공연\" main-selected=\"false\">공연</a>\n");
      out.write("                            <ul>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/rmovie.pr?ctype=뮤지컬\" class=\"minCategory\">뮤지컬</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/rmovie.pr?ctype=연극\" class=\"minCategory\">연극</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/rmovie.pr?ctype=클래식\" class=\"minCategory\">클래식</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/rmovie.pr?ctype=콘서트\" class=\"minCategory\">콘서트</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                            <li  style=\"width: 2px; height: 20px; margin-top: 8px; background-color: #515155;\"></li>\n");
      out.write("                        <li><a href=\"");
      out.print( contextPath );
      out.write("/prcrank.pr?ctype=랭킹\" class=\"main_category\" id=\"랭킹\" main-selected=\"false\">랭킹</a></li>\n");
      out.write("                        <li><a href=\"");
      out.print( contextPath );
      out.write("/lolist.pr?ctype=서울\" class=\"main_category\" id=\"지역\" main-selected=\"false\">지역</a>\n");
      out.write("                            <ul class=\"local\">\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/lolist.pr?ctype=서울\" class=\"minCategory\">서울</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/lolist.pr?ctype=경기\" class=\"minCategory\">경기/이천</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/lolist.pr?ctype=충청\" class=\"minCategory\">충청/강원</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/lolist.pr?ctype=경상\" class=\"minCategory\">경상</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/lolist.pr?ctype=전라\" class=\"minCategory\">전라</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/lolist.pr?ctype=제주\" class=\"minCategory\">제주</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        \n");
      out.write("                        </li>\n");
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("                    <div class=\"header_search_box\" > <!-- 검색 -->\n");
      out.write("                    	<form action=\"");
      out.print( contextPath );
      out.write("/search.pr\">\n");
      out.write("                        <input type=\"search\" name=\"sKeyWord\" id=\"search\" class=\"header_search_input\" placeholder=\"검색어를 입력해 주세요\">\n");
      out.write("                        <button type=\"submit\" id=\"btnImg\"><img src=\"resource/search.png\" id=\"btn_Img\" ></button>\n");
      out.write("                   		</form>\n");
      out.write("                    </div>           \n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>    \n");
      out.write("    </div>\n");
      out.write("  	\n");
      out.write("    \n");
      out.write("            \n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 내용 넣을 수 있는 구간 시작 -->\n");
      out.write("\n");
      out.write("<div class=\"원하는데로_바꾸세요\">\n");
      out.write("    <div class=\"servicecenter\">\n");
      out.write("        <h1 align=\"center\">고객센터</h1>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"servicefunction\">\n");
      out.write("        <!-- 바디의 왼쪽메뉴-->\n");
      out.write("        <div class=\"leftmenu\">\n");
      out.write("            <div onclick=\"location.href='");
      out.print(contextPath );
      out.write("/customer.cu'\">고객센터 홈</div>\n");
      out.write("            <div id=\"announce\" style=\"color:red\" onclick=\"location.href='");
      out.print(contextPath );
      out.write("/list.no';\">공지사항 </div>\n");
      out.write("            <div onclick=\"location.href='");
      out.print(contextPath );
      out.write("/list.qo'\">Q&A</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("       \n");
      out.write("       \n");
      out.write("        <!-- 바디의 오른쪽메뉴-->\n");
      out.write("        <div class=\"rightmenu\">\n");
      out.write("            <h2 align=\"center\">공지사항</h2>\n");
      out.write("            <img id=\"event\" src=\"resource/이미지자료/이벤트.png\">\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            <!--  현재 로그인한 사용자가 관리자 일 경우 보여질 div -->\n");
      out.write("            ");
 if(loginMember !=null && loginMember.getUserId().equals("admin"))  {
      out.write("\n");
      out.write("            <div align =\"right\" style=\"width: 870px;\">\n");
      out.write("            \n");
      out.write("            <button onclick=\"location.href='");
      out.print(contextPath );
      out.write("/enrollForm.no'\">글작성</button>\n");
      out.write("        \n");
      out.write("        </div>\n");
      out.write("        ");
} 
      out.write("\n");
      out.write("            \n");
      out.write("            <table class=\"rightmain\">\n");
      out.write("                <thead>\n");
      out.write("                <tr id=\"tr1\">\n");
      out.write("                    <td>번호</td>\n");
      out.write("                    <td colspan=\"2\">제목</td>\n");
      out.write("                    <td>조회수</td>\n");
      out.write("                </tr>\n");
      out.write("                </thead>\n");
      out.write("      \n");
      out.write("                <tbody>\n");
      out.write("      				<!--1. 공지글이 없는 경우-->\n");
      out.write("      				");
if(list.isEmpty()){ 
      out.write("\n");
      out.write("      				\n");
      out.write("      				<tr>\n");
      out.write("      					<td colsapn=\"5\">존재하는 공지사항이 없습니다.</td>\n");
      out.write("      				</tr>\n");
      out.write("      			   ");
}else { 
      out.write("\n");
      out.write("      			   	   <!-- 2. 공지글이 있을 경우 -->\n");
      out.write("      			   	   ");
for(Notice n:list){ 
      out.write("\n");
      out.write("      			   	   <tr>\n");
      out.write("      			   	   		<th>");
      out.print(n.getNoticeNo() );
      out.write("</th>\n");
      out.write("      			   	   		<th colspan=\"2\">");
      out.print(n.getNoticeTitle() );
      out.write("</th>\n");
      out.write("      			   	   		<th>");
      out.print(n.getNoticeCount() );
      out.write("</th>\n");
      out.write("      			   	   </tr>\n");
      out.write("      			   	   ");
} 
      out.write("\n");
      out.write("      			   ");
} 
      out.write("       \n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 내용물 넣을 수 있는 구간 끝 -->\n");
      out.write("    <!-- 바디 끝 -->\n");
      out.write("    <script>\n");
      out.write("        $(function(){\n");
      out.write("            $(\".leftmenu>.lm\").hover().css(\"cursor\",\"pointer\");\n");
      out.write("            $(\".rightmain>tbody>tr\").hover().css(\"cursor\",\"pointer\");\n");
      out.write("            $(\".rightmain>tbody>tr\").click(function(){\n");
      out.write("            	const num = $(this).children().eq(0).text()\n");
      out.write("            	\n");
      out.write("            	location.href = '");
      out.print(contextPath);
      out.write("/detail.no?num=' + num;\n");
      out.write("            });\n");
      out.write("           \n");
      out.write("        })\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>티켓딱대</title>\n");
      out.write("<style>\n");
      out.write("	/* 푸터 시작 */\n");
      out.write("    div{\n");
      out.write("        /* border: 1px solid pink; */\n");
      out.write("        box-sizing: border-box;\n");
      out.write("        \n");
      out.write("    }\n");
      out.write("    .footer{\n");
      out.write("        border-top: 1px solid #f8f8f8 ;\n");
      out.write("    }\n");
      out.write("    #footer>div{width: 100%;}\n");
      out.write("\n");
      out.write("\n");
      out.write("    #footer_1{\n");
      out.write("        width: 1120px;\n");
      out.write("        height: 30px;  \n");
      out.write("        border-top: 1px; \n");
      out.write("        margin: auto; \n");
      out.write("        margin-top: 10px;\n");
      out.write("        margin-left: 350px;\n");
      out.write("        /* border: 1px solid red; */\n");
      out.write("    } \n");
      out.write("    #footer_1>a{\n");
      out.write("        text-decoration: none;\n");
      out.write("        color: black;\n");
      out.write("        font-size: 13px;\n");
      out.write("        font-weight: 500;\n");
      out.write("        margin: 15px; \n");
      out.write("    }\n");
      out.write("    #footer_2{\n");
      out.write("        height: 80%;\n");
      out.write("        border-top: 2px solid rgba(212, 212, 212, 0.459);\n");
      out.write("        /* border: 1px solid red; */\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    #p1{\n");
      out.write("        width: 1120px; \n");
      out.write("        height: 80%;\n");
      out.write("        /* margin: auto;  */\n");
      out.write("        padding: 5px 15px;\n");
      out.write("        /* background-color: #878d95; */\n");
      out.write("        margin-left: 350px;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    #footer_2>p{\n");
      out.write("        /* width: 100%; */\n");
      out.write("        /* border: 1px solid blueviolet; */\n");
      out.write("        box-sizing: border-box;\n");
      out.write("        /* margin: auto; */\n");
      out.write("        font-size: 12px;\n");
      out.write("        /* color:rgb(58, 58, 58); */\n");
      out.write("        \n");
      out.write("    }\n");
      out.write("    #p2{\n");
      out.write("        height: 20%; \n");
      out.write("        text-align: center; \n");
      out.write("        padding-bottom: 15px;\n");
      out.write("        padding-top: 10px; \n");
      out.write("        color: rgba(184, 184, 184, 0.747);\n");
      out.write("        font-weight: 800;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("   \n");
      out.write("    /* 푸터 끝 */\n");
      out.write("    /* top버튼 */\n");
      out.write("    #backToTopBtn {\n");
      out.write("    display: none;\n");
      out.write("    position: fixed;\n");
      out.write("    bottom: 20px;\n");
      out.write("    right: 200px;\n");
      out.write("    width: 60px;\n");
      out.write("    height: 40px;\n");
      out.write("    background-color: white;\n");
      out.write("    color: rgb(253, 103, 103);\n");
      out.write("    border: 1px solid rgba(206, 206, 206, 0.671);\n");
      out.write("    border-radius: 5px;\n");
      out.write("    font-size: 20px;\n");
      out.write("    font-weight: 600;\n");
      out.write("    cursor: pointer;\n");
      out.write("    border-radius: 38px;\n");
      out.write("    line-height: 0;\n");
      out.write("    \n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"footer\">\n");
      out.write("        <div id=\"footer_1\">\n");
      out.write("            <a href=\"#\">이용약관</a>|\n");
      out.write("            <a href=\"#\">개인정보취급방침</a>|\n");
      out.write("            <a href=\"#\">인재채용</a>|\n");
      out.write("            <a href=\"#\">고객센터</a>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"footer_2\">\n");
      out.write("            <P id=\"p1\">\n");
      out.write("                <br>\n");
      out.write("                이눔식기 주식회사 <br><br>\n");
      out.write("\n");
      out.write("                주소 :  서울특별시 강남구 테헤란로14길 6 남도빌딩 3F H-class | 대표이사 : 김시연 | 사업자등록번호 : 없떵<br>\n");
      out.write("                010-2646-7652 | @naver.com | 개발자코스 : 종일반 | 사업자정보확인 | 개인정보보호책임자 : 김시연\n");
      out.write("            </P>\n");
      out.write("            <p id=\"p2\">\n");
      out.write("                Copyright © 1998-2023 KH Information Educational Institute All Right Reserved\n");
      out.write("            </p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Back to top button -->\n");
      out.write("        <button id=\"backToTopBtn\">Top</button>\n");
      out.write("        \n");
      out.write("        <!-- Anchor element representing the top of the page -->\n");
      out.write("        <a href=\"#top\" id=\"topAnchor\"></a>\n");
      out.write("        \n");
      out.write("        <!-- Your script files can go here -->\n");
      out.write("        \n");
      out.write("        <script>\n");
      out.write("            // When the page is fully loaded\n");
      out.write("            window.onload = function () {\n");
      out.write("                var backToTopBtn = document.getElementById(\"backToTopBtn\");\n");
      out.write("                var topAnchor = document.getElementById(\"topAnchor\");\n");
      out.write("                \n");
      out.write("                // Show/hide the back-to-top button based on scroll position\n");
      out.write("                window.onscroll = function () {\n");
      out.write("                    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {\n");
      out.write("                        backToTopBtn.style.display = \"block\";\n");
      out.write("                    } else {\n");
      out.write("                        backToTopBtn.style.display = \"none\";\n");
      out.write("                    }\n");
      out.write("                };\n");
      out.write("                \n");
      out.write("                // Scroll to the top when the button is clicked\n");
      out.write("                backToTopBtn.onclick = function () {\n");
      out.write("                    document.documentElement.scrollTop = 0;\n");
      out.write("                };\n");
      out.write("            };\n");
      out.write("        </script>\n");
      out.write("    \n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
