/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-07 08:36:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manager_002dregist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/manager/regist/regist.jsp", Long.valueOf(1694057600000L));
    _jspx_dependants.put("/views/manager/regist/regist-bar.jsp", Long.valueOf(1694057600000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\n");
      out.write("  <title>관리자 페이지</title>\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\n");
      out.write("  <style>\n");
      out.write("    body{\n");
      out.write("      font-family: 'Jua', sans-serif;\n");
      out.write("    }\n");
      out.write("    .wrapper .divd{\n");
      out.write("      box-sizing: border-box;\n");
      out.write("      border: 1px solid #ABBBC7;\n");
      out.write("      text-align: center;\n");
      out.write("    }\n");
      out.write("    .wrapper{\n");
      out.write("        width: 1200px;\n");
      out.write("        height: 762px;\n");
      out.write("        margin: auto;\n");
      out.write("        background-color: #C9D9E6;\n");
      out.write("    }  \n");
      out.write("    .container1{\n");
      out.write("      height: 100%;\n");
      out.write("      width: 15%;\n");
      out.write("    }\n");
      out.write("    .container2{\n");
      out.write("      height: 100%;\n");
      out.write("      width: 85%;\n");
      out.write("    }\n");
      out.write("    .wrapper{\n");
      out.write("      display: flex;\n");
      out.write("    }\n");
      out.write("    .content1{\n");
      out.write("      width: 100%;\n");
      out.write("      height: 11%;\n");
      out.write("    }\n");
      out.write("    .content2{\n");
      out.write("      width: 100%;\n");
      out.write("      height: 89%;\n");
      out.write("    }\n");
      out.write("    .container1>div{\n");
      out.write("      border: 1px solid #ABBBC7;\n");
      out.write("      width: 100%;\n");
      out.write("      height: 50px;\n");
      out.write("      line-height: 30px;\n");
      out.write("      text-align: center;\n");
      out.write("      border-radius: 0;\n");
      out.write("      cursor: pointer;\n");
      out.write("        }\n");
      out.write("    .container1 .box:nth-child(2){\n");
      out.write("      border-top-left-radius: 5px;\n");
      out.write("      border-top-right-radius: 5px;\n");
      out.write("    }\n");
      out.write("    .container1 .box:nth-child(19){\n");
      out.write("      border-bottom-left-radius: 5px;\n");
      out.write("      border-bottom-right-radius: 5px;\n");
      out.write("    }\n");
      out.write("    .container1>p{\n");
      out.write("      width: 100%;\n");
      out.write("      height: 20px;\n");
      out.write("      border-radius: 10px;\n");
      out.write("      margin-top: 5px;\n");
      out.write("      padding: 10px;\n");
      out.write("      box-sizing: border-box;\n");
      out.write("      text-align: left;\n");
      out.write("      }\n");
      out.write("      .wrapper{\n");
      out.write("        border-radius: 5px;\n");
      out.write("      }\n");
      out.write("      .container1{\n");
      out.write("        border-top-left-radius: 5px;\n");
      out.write("        border-bottom-left-radius: 5px;\n");
      out.write("      }\n");
      out.write("      .container2{\n");
      out.write("        border-top-right-radius: 5px;\n");
      out.write("        border-bottom-right-radius: 5px;\n");
      out.write("      }\n");
      out.write("      .content1{\n");
      out.write("        border-top-right-radius: 5px;\n");
      out.write("        border-bottom-right-radius: 5px;\n");
      out.write("      }\n");
      out.write("      .content2{\n");
      out.write("        border-top-right-radius: 5px;\n");
      out.write("        border-bottom-right-radius: 5px;\n");
      out.write("      }\n");
      out.write("      iframe{\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("      }\n");
      out.write("      .style1{\n");
      out.write("        font-weight: bold;\n");
      out.write("        background-color: #C9D9E6;\n");
      out.write("      }\n");
      out.write("      .p1{\n");
      out.write("        font-weight: bold;\n");
      out.write("        background-color: #C9D9E6;\n");
      out.write("        cursor: pointer;\n");
      out.write("      }\n");
      out.write("      .p1:hover{\n");
      out.write("        background-color: #ABBBC7;\n");
      out.write("      }\n");
      out.write("      .box-with-shadow {\n");
      out.write("        box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);\n");
      out.write("      }\n");
      out.write("      #container3 {\n");
      out.write(" 		position: relative;\n");
      out.write("	  }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <div class=\"wrapper box-with-shadow divd\" style=\"margin-top: 64px;\">\n");
      out.write("    <div class=\"container1 divd\">\n");
      out.write("      <h3 style=\"font-size: 30px; margin-top: 42px; margin-bottom: 37px;\"><a href=\"/semi01\">관리자</a></h3>\n");
      out.write("    \n");
      out.write("      <!-- 회원관심태그 조회, 회원삭제, 회원 등급조정, 신고내역확인 -->\n");
      out.write("      <div class=\"box style1 divd\" style=\"line-height: 3;\">회원관리</div>\n");
      out.write("      <p class=\"p1\" style=\"padding-bottom: 30px; margin-bottom: 0; margin-top: 0; border-radius: 0;\">회원조회</p>\n");
      out.write("      <!--\n");
      out.write("      <p class=\"p1\">회원관심태그 조회</p>\n");
      out.write("      <p class=\"p1\">회원삭제</p>\n");
      out.write("      <p class=\"p1\">회원 등급조정</p>\n");
      out.write("      <p class=\"p1\">신고내역확인</p>\n");
      out.write("      -->\n");
      out.write("      <!--\n");
      out.write("      <div class=\"style1\" style=\"line-height: 3;\">고객센터 관리</div>\n");
      out.write("      <p class=\"p1\">공지사항 조회</p>\n");
      out.write("      <p class=\"p1\">공지사항 수정</p>\n");
      out.write("      <p class=\"p1\">공지사항 삭제</p>\n");
      out.write("      <p class=\"p1\">Q&A 수정</p>\n");
      out.write("      -->\n");
      out.write("      <div class=\"style1 divd\" style=\"line-height: 3;\">상품관리</div>\n");
      out.write("      <p class=\"p1\" style=\"margin-top: 0; margin-bottom: 0; padding-top: 10px; padding-bottom: 30px; border-radius: 0;\">상품조회</p>\n");
      out.write("      <p class=\"p1\" style=\"margin-top: 0; margin-bottom: 0; border-bottom: 1px solid #ABBBC7; padding-top: 10px; padding-bottom: 30px; border-radius: 0;\">상품등록</p>\n");
      out.write("      <!--\n");
      out.write("      <p class=\"p1\">상품수정</p>\n");
      out.write("      <p class=\"p1 p3\">상품삭제</p>\n");
      out.write("      <p class=\"p1 p3\">리뷰조회</p>\n");
      out.write("      <p class=\"p1 p3\" style=\"margin: 0; padding-bottom: 30px; border-left: 1px solid #ABBBC7; border-right: 1px solid #ABBBC7; border-radius: 0;\">리뷰삭제</p>\n");
      out.write("      -->\n");
      out.write("      <!-- \n");
      out.write("      <div class=\"box style1 divd\" style=\"line-height: 3; border-bottom: 2px solid #ABBBC7;\">통계</div>\n");
      out.write("      <p class=\"p1\" style=\"padding-bottom: 32px; margin: 0; height: 35px; border-radius: 0; border-right: 1px solid #ABBBC7; border-left: 1px solid #ABBBC7; border-radius: 0;\">판매통계</p>\n");
      out.write("      <p class=\"p1\" style=\"margin: 0; height: 35px; border-radius: 0; border-right: 1px solid #ABBBC7; border-left: 1px solid #ABBBC7; padding-bottom: 32px; border-radius: 0;\">이용자 통계</p>\n");
      out.write("      <p class=\"p1\" style=\"margin: 0; height: 35px; border-radius: 0; border-right: 1px solid #ABBBC7; border-left: 1px solid #ABBBC7; border-bottom: 1px solid #ABBBC7; padding-bottom: 32px; border-radius: 0;\">카테고리 통계</p>\n");
      out.write("      -->\n");
      out.write("      <!--\n");
      out.write("      <p class=\"p1\" style=\"margin: 0; height: 35px; border-right: 1px solid #ABBBC7; border-left: 1px solid #ABBBC7; border-bottom: 1px solid #ABBBC7; padding-bottom: 32px; border-radius: 0;\">상품별 좋아요 통계</p>\n");
      out.write("      -->\n");
      out.write("    </div>\n");
      out.write("    <div class=\"container2 divd\">\n");
      out.write("      <div class=\"content1 divd\" id=\"bar\" style=\"border-bottom-right-radius: 0;\">\n");
      out.write("      	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Document</title>\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\n");
      out.write("  <style>\n");
      out.write("    body{\n");
      out.write("      font-family: 'Jua', sans-serif;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <h2 style=\"margin-top: 30px; text-align: left; margin-left: 4px;\">상품등록</h2>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("        <!-- <iframe src=\"member-bar.html\" frameborder=\"0\"></iframe> -->\n");
      out.write("        <!-- <iframe src=\"regist-bar.html\" frameborder=\"0\"></iframe> -->\n");
      out.write("        <!-- <iframe src=\"goodsList-bar.html\" frameborder=\"0\"></iframe> -->\n");
      out.write("        <!-- <iframe src=\"salesStatitics-bar.html\" frameborder=\"0\"></iframe> -->\n");
      out.write("        <!-- <iframe src=\"userStatitics-bar.html\" frameborder=\"0\"></iframe> -->\n");
      out.write("        <!-- <iframe src=\"categoryStatitics-bar.html\" frameborder=\"0\"></iframe> -->\n");
      out.write("      </div>\n");
      out.write("      <div class=\"content2 divd\" style=\"background-color: rgb(237, 237, 237); border-top-right-radius: 0;\" id=\"container3\">\n");
      out.write("      	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Document</title>\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\n");
      out.write("  <style>\n");
      out.write("    div{box-sizing: border-box;}\n");
      out.write("    body{\n");
      out.write("      font-family: 'Jua', sans-serif;\n");
      out.write("    }\n");
      out.write("    #goodsform input[type=\"text\"], #goodsform input[type=\"number\"]{\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 5px;\n");
      out.write("        height: 30px;\n");
      out.write("        width: 89%;\n");
      out.write("    }\n");
      out.write("    #bts3{\n");
      out.write("        display: block;\n");
      out.write("        width: 20%;\n");
      out.write("        height: 50px;\n");
      out.write("        margin-top: 55px;\n");
      out.write("        background-color: rgb(171, 187, 199);\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 5px;\n");
      out.write("        font-size: 15px;\n");
      out.write("        font-weight: bold;\n");
      out.write("        margin: auto;\n");
      out.write("        margin-top: 62px;\n");
      out.write("    }\n");
      out.write("    #bts3:hover{\n");
      out.write("        background-color: darkgray;\n");
      out.write("        cursor: pointer;\n");
      out.write("    }\n");
      out.write("    tr{\n");
      out.write("        height: 50px;\n");
      out.write("    }\n");
      out.write("    td{\n");
      out.write("        padding: 0px;\n");
      out.write("        font-size: 15px;\n");
      out.write("        font-weight: bold;\n");
      out.write("    }\n");
      out.write("    table{\n");
      out.write("        width: 50%;\n");
      out.write("    }\n");
      out.write("    #container{\n");
      out.write("        display: flex;\n");
      out.write("    }\n");
      out.write("    .custom-file-input {\n");
      out.write("    visibility: hidden; /* 기본 파일 선택 버튼 숨김 */\n");
      out.write("    display: none;\n");
      out.write("    width: 0;\n");
      out.write("    height: 0;\n");
      out.write("    }\n");
      out.write("    .custom-file-label {\n");
      out.write("    background-color:#ABBBC7;\n");
      out.write("    display: block;\n");
      out.write("    width: 10%;\n");
      out.write("    border:none;\n");
      out.write("    padding: 6px 12px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    font-weight: bold;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    margin-top: 11px;\n");
      out.write("    height: 21px;\n");
      out.write("    text-align: center;\n");
      out.write("    line-height: 1.5;\n");
      out.write("    }\n");
      out.write("    #filePath1, #filePath2, #filePath3, #filePath4, #filePath5, #filePath6{\n");
      out.write("        display: block;\n");
      out.write("        width: 56%;\n");
      out.write("        margin-top: 11px;\n");
      out.write("        margin-left: 14px;\n");
      out.write("    }\n");
      out.write("    #imageDisplay{\n");
      out.write("        margin-left: 76px;\n");
      out.write("        margin-top: 20px;\n");
      out.write("        width: 300px;\n");
      out.write("        height: 292px;\n");
      out.write("        background-color: white;\n");
      out.write("        position: relative;\n");
      out.write("        border-radius: 5px;\n");
      out.write("    }\n");
      out.write("    img{\n");
      out.write("        display: block;\n");
      out.write("        width: 300px;\n");
      out.write("        height: 292px;\n");
      out.write("        border-radius: 5px;\n");
      out.write("    }\n");
      out.write("    #text{\n");
      out.write("        text-align: center;\n");
      out.write("        top:109px;\n");
      out.write("        left:110px;\n");
      out.write("        position:absolute;\n");
      out.write("    }\n");
      out.write("    #date1, #span1, #date2{\n");
      out.write("        display: block;\n");
      out.write("    }\n");
      out.write("    input[type=\"date\"]{\n");
      out.write("        width: 144px;\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 5px;\n");
      out.write("        height: 30px;\n");
      out.write("        width: 42%;\n");
      out.write("        font-weight: bold;\n");
      out.write("    }\n");
      out.write("    .labels{\n");
      out.write("        font-size: 13px;\n");
      out.write("    }\n");
      out.write("    .sel101{\n");
      out.write("        border: none;\n");
      out.write("        display: block;\n");
      out.write("        width: 100px;\n");
      out.write("        height: 30px;\n");
      out.write("        border-radius: 5px;\n");
      out.write("        font-weight: bold;\n");
      out.write("    }\n");
      out.write("    #tb9 td{\n");
      out.write("    	text-align: left;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <form action=\"/manager-regist-product.do\" method=\"post\" id=\"goodsform\" style=\"margin-left: 38px;\" enctype=\"multipart/form-data\">\n");
      out.write("    <div id=\"container\" style=\"margin-top: 13px;\">\n");
      out.write("        <table id=\"tb9\">\n");
      out.write("            <tr>\n");
      out.write("                <td>카테고리</td>\n");
      out.write("                <td style=\"display: flex; margin-top: 10px;\">\n");
      out.write("                    <select id=\"selects1\" name=\"salsa1\" class=\"sel101\" style=\"margin-right: 13px; font-family: 'Jua', sans-serif;\">\n");
      out.write("                        <option value=\"movie\">영화</option>\n");
      out.write("                        <option value=\"display\">전시</option>\n");
      out.write("                        <option value=\"show\">공연</option>\n");
      out.write("                    </select>\n");
      out.write("                    <select id=\"selects2\" name=\"salsa2\" class=\"sel101\" style=\"font-family: 'Jua', sans-serif;\">\n");
      out.write("                        <option value=\"1\">로맨스</option>\n");
      out.write("                        <option value=\"2\">공포/스릴러</option>\n");
      out.write("                        <option value=\"3\">코미디</option>\n");
      out.write("                        <option value=\"4\">액션</option>\n");
      out.write("                    </select>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td style=\"width: 23%;\">제목</td>\n");
      out.write("                <td>\n");
      out.write("                    <input type=\"text\" name=\"title\" id=\"title\" placeholder=\"제목을 입력하시오\" style=\"font-family: 'Jua', sans-serif;\">\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>지역</td>\n");
      out.write("                <td>\n");
      out.write("                    <select id=\"selects3\" name=\"salsa3\" class=\"sel101\" style=\"font-family: 'Jua', sans-serif;\">\n");
      out.write("                        <option value=\"1\">서울</option>\n");
      out.write("                        <option value=\"2\">경기/인천</option>\n");
      out.write("                        <option value=\"3\">충청/강원</option>\n");
      out.write("                        <option value=\"4\">대구/경북</option>\n");
      out.write("                        <option value=\"5\">광주/전라</option>\n");
      out.write("                        <option value=\"6\">제주</option>\n");
      out.write("                    </select>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>상세주소</td>\n");
      out.write("                <td>\n");
      out.write("                    <input type=\"text\" name=\"place\" id=\"place\" placeholder=\"상세주소를 입력하시오\" style=\"font-family: 'Jua', sans-serif;\">\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>관람시간(분)</td>\n");
      out.write("                <td>\n");
      out.write("                    <input type=\"number\" name=\"time\" id=\"time\" placeholder=\"관람시간을 입력하시오\" style=\"width: 150px; font-family: 'Jua', sans-serif;\">\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>기간</td>\n");
      out.write("                <td style=\"display: flex; margin-top: 9px;\">\n");
      out.write("                    <input type=\"date\" name=\"date1\" id=\"date1\" style=\"font-family: 'Jua', sans-serif;\">\n");
      out.write("                    <span id=\"span1\" style=\"line-height: 2.5;\">&nbsp;~&nbsp;</span>\n");
      out.write("                    <input type=\"date\" name=\"date2\" id=\"date2\" style=\"font-family: 'Jua', sans-serif;\">\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>시간</td>\n");
      out.write("                <td>\n");
      out.write("                    <select id=\"select1\" name=\"salsa4\" class=\"sel101\" style=\"font-family: 'Jua', sans-serif;\">\n");
      out.write("                        <option value=\"오전\">오전</option>\n");
      out.write("                        <option value=\"오후\">오후</option>\n");
      out.write("                        <option value=\"전체\">전체</option>\n");
      out.write("                    </select>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>관람등급</td>\n");
      out.write("                <td>\n");
      out.write("                    <select id=\"select1\" name=\"salsa5\" class=\"sel101\" style=\"font-family: 'Jua', sans-serif;\">\n");
      out.write("                        <option value=\"1\">전체</option>\n");
      out.write("                        <option value=\"2\">7</option>\n");
      out.write("                        <option value=\"3\">12</option>\n");
      out.write("                        <option value=\"4\">15</option>\n");
      out.write("                        <option value=\"5\">19</option>\n");
      out.write("                    </select>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>가격</td>\n");
      out.write("                <td>\n");
      out.write("                    <input type=\"number\" name=\"price\" id=\"price\" placeholder=\"가격을 입력하시오\" style=\"width: 150px; font-family: 'Jua', sans-serif;\">\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>좌석수</td>\n");
      out.write("                <td>\n");
      out.write("                    <input type=\"number\" name=\"seatsNum\" id=\"price\" placeholder=\"좌석수를 입력하시오\" style=\"width: 150px; font-family: 'Jua', sans-serif;\">\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("        <div style=\"width: 50%; margin-top: 52px;\">\n");
      out.write("            <div style=\"display: flex;\">\n");
      out.write("                <label class=\"custom-file-label\" for=\"customFile1\" style=\"margin-left: 50px;\">\n");
      out.write("                    포스터\n");
      out.write("                </label>\n");
      out.write("                <input type=\"file\" id=\"customFile1\" name=\"customFile1\" class=\"custom-file-input\">\n");
      out.write("                <input type=\"text\" id=\"filePath1\" placeholder=\"사진을 선택하시오\" style=\"width: 48%; font-family: 'Jua', sans-serif;\">\n");
      out.write("            </div>\n");
      out.write("            <div style=\"display: flex; margin-top: 8px;\">\n");
      out.write("                <label class=\"custom-file-label\" for=\"customFile2\" style=\"margin-left: 50px;\">\n");
      out.write("                    상세1\n");
      out.write("                </label>\n");
      out.write("                <input type=\"file\" id=\"customFile2\" name=\"customFile2\" class=\"custom-file-input\">\n");
      out.write("                <input type=\"text\" id=\"filePath2\" placeholder=\"사진을 선택하시오\" style=\"width: 48%; font-family: 'Jua', sans-serif;\">\n");
      out.write("            </div>\n");
      out.write("            <div style=\"display: flex; margin-top: 8px;\">\n");
      out.write("                <label class=\"custom-file-label\" for=\"customFile3\" style=\"margin-left: 50px;\">\n");
      out.write("                    상세2\n");
      out.write("                </label>\n");
      out.write("                <input type=\"file\" id=\"customFile3\" name=\"customFile3\" class=\"custom-file-input\">\n");
      out.write("                <input type=\"text\" id=\"filePath3\" placeholder=\"사진을 선택하시오\" style=\"width: 48%; font-family: 'Jua', sans-serif;\">\n");
      out.write("            </div>\n");
      out.write("            <div style=\"display: flex; margin-top: 8px;\">\n");
      out.write("                <label class=\"custom-file-label\" for=\"customFile4\" style=\"margin-left: 50px;\">\n");
      out.write("                    상세3\n");
      out.write("                </label>\n");
      out.write("                <input type=\"file\" id=\"customFile4\" name=\"customFile4\" class=\"custom-file-input\">\n");
      out.write("                <input type=\"text\" id=\"filePath4\" placeholder=\"사진을 선택하시오\" style=\"width: 48%; font-family: 'Jua', sans-serif;\">\n");
      out.write("            </div>\n");
      out.write("            <div style=\"display: flex; margin-top: 8px;\">\n");
      out.write("                <label class=\"custom-file-label\" for=\"customFile5\" style=\"margin-left: 50px;\">\n");
      out.write("                    상세4\n");
      out.write("                </label>\n");
      out.write("                <input type=\"file\" id=\"customFile5\" name=\"customFile5\" class=\"custom-file-input\">\n");
      out.write("                <input type=\"text\" id=\"filePath5\" placeholder=\"사진을 선택하시오\" style=\"width: 48%; font-family: 'Jua', sans-serif;\">\n");
      out.write("            </div>\n");
      out.write("            <div style=\"display: flex; margin-top: 8px;\">\n");
      out.write("                <label class=\"custom-file-label\" for=\"customFile6\" style=\"margin-left: 50px;\">\n");
      out.write("                    상세5\n");
      out.write("                </label>\n");
      out.write("                <input type=\"file\" id=\"customFile6\" name=\"customFile6\" class=\"custom-file-input\">\n");
      out.write("                <input type=\"text\" id=\"filePath6\" placeholder=\"사진을 선택하시오\" style=\"width: 48%; font-family: 'Jua', sans-serif;\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <button id=\"bts3\" type=\"submit\" style=\"margin-top: 35px; font-family: 'Jua', sans-serif;\">등록</button>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    $(function(){\n");
      out.write("   	    $('#selects1').on('change', function() {\n");
      out.write("   	        var selectedValue = $(this).val();\n");
      out.write("   	        $.ajax({\n");
      out.write("   	            url: \"manager-regist-selectbox.do\",\n");
      out.write("   	            type: 'GET',\n");
      out.write("   	            data: {selectedValue:selectedValue},\n");
      out.write("   	            dataType: 'json',\n");
      out.write("   	            success: function(response) {\n");
      out.write("   	            $(\"#selects2\").empty();\n");
      out.write("   	             response.forEach(item => {\n");
      out.write("   	            	$('#selects2').append($('<option>', {\n");
      out.write("   	                  value: item.categoryType,\n");
      out.write("   	                  text: item.categoryName\n");
      out.write("   	              }));\n");
      out.write("   	          });\n");
      out.write("   	                \n");
      out.write("   	            },\n");
      out.write("   	            error: function() {\n");
      out.write("   	                console.log(\"에러\");\n");
      out.write("   	            }\n");
      out.write("   	        });\n");
      out.write("   	    });\n");
      out.write("    	const imageInput1 = document.getElementById('customFile1');\n");
      out.write("        const imagePathInput1 = document.getElementById('filePath1');\n");
      out.write("\n");
      out.write("        imageInput1.addEventListener('change', function(event) {\n");
      out.write("        const selectedFile = event.target.files[0]; // 선택한 파일의 정보 가져오기\n");
      out.write("            if (selectedFile) {\n");
      out.write("                const fileName = selectedFile.name;\n");
      out.write("                imagePathInput1.value = fileName; // 입력란에 경로 설정\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        const imageInput2 = document.getElementById('customFile2');\n");
      out.write("        const imagePathInput2 = document.getElementById('filePath2');\n");
      out.write("\n");
      out.write("        imageInput2.addEventListener('change', function(event) {\n");
      out.write("        const selectedFile = event.target.files[0]; // 선택한 파일의 정보 가져오기\n");
      out.write("            if (selectedFile) {\n");
      out.write("                const fileName = selectedFile.name;\n");
      out.write("                imagePathInput2.value = fileName; // 입력란에 경로 설정\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        const imageInput3 = document.getElementById('customFile3');\n");
      out.write("        const imagePathInput3 = document.getElementById('filePath3');\n");
      out.write("\n");
      out.write("        imageInput3.addEventListener('change', function(event) {\n");
      out.write("        const selectedFile = event.target.files[0]; // 선택한 파일의 정보 가져오기\n");
      out.write("            if (selectedFile) {\n");
      out.write("                const fileName = selectedFile.name;\n");
      out.write("                imagePathInput3.value = fileName; // 입력란에 경로 설정\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        const imageInput4 = document.getElementById('customFile4');\n");
      out.write("        const imagePathInput4 = document.getElementById('filePath4');\n");
      out.write("\n");
      out.write("        imageInput4.addEventListener('change', function(event) {\n");
      out.write("        const selectedFile = event.target.files[0]; // 선택한 파일의 정보 가져오기\n");
      out.write("            if (selectedFile) {\n");
      out.write("                const fileName = selectedFile.name;\n");
      out.write("                imagePathInput4.value = fileName; // 입력란에 경로 설정\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        const imageInput5 = document.getElementById('customFile5');\n");
      out.write("        const imagePathInput5 = document.getElementById('filePath5');\n");
      out.write("\n");
      out.write("        imageInput5.addEventListener('change', function(event) {\n");
      out.write("        const selectedFile = event.target.files[0]; // 선택한 파일의 정보 가져오기\n");
      out.write("            if (selectedFile) {\n");
      out.write("                const fileName = selectedFile.name;\n");
      out.write("                imagePathInput5.value = fileName; // 입력란에 경로 설정\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        const imageInput6 = document.getElementById('customFile6');\n");
      out.write("        const imagePathInput6 = document.getElementById('filePath6');\n");
      out.write("\n");
      out.write("        imageInput6.addEventListener('change', function(event) {\n");
      out.write("        const selectedFile = event.target.files[0]; // 선택한 파일의 정보 가져오기\n");
      out.write("            if (selectedFile) {\n");
      out.write("                const fileName = selectedFile.name;\n");
      out.write("                imagePathInput6.value = fileName; // 입력란에 경로 설정\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("        <!-- <iframe src=\"regist.html\" frameborder=\"0\"></iframe> -->\n");
      out.write("        <!-- <iframe src=\"member.html\" frameborder=\"0\"></iframe> -->\n");
      out.write("        <!-- <iframe src=\"goodsList.html\" frameborder=\"0\"></iframe> -->\n");
      out.write("        <!-- <iframe src=\"salesStatitics-1.html\" frameborder=\"0\"></iframe> -->\n");
      out.write("        <!-- <iframe src=\"salesStatitics-2.html\" frameborder=\"0\"></iframe> -->\n");
      out.write("        <!-- <iframe src=\"userStatitics.html\" frameborder=\"0\"></iframe> -->\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <script>\n");
      out.write("    $(function(){\n");
      out.write("        $(\".p1\").click(function(){\n");
      out.write("          var p1content = $(this).text();\n");
      out.write("          console.log(p1content);\n");
      out.write("          \n");
      out.write("          if(p1content == \"회원조회\"){\n");
      out.write("        	  var form = $(\"<form>\", {\n");
      out.write("                  action: \"manager-member.do\", // 서블릿의 URL\n");
      out.write("                  method: \"get\",\n");
      out.write("                  style: \"display: none;\" // 폼을 안보이도록 스타일링\n");
      out.write("              });\n");
      out.write("        	  \n");
      out.write("        	  form.append($(\"<input>\", {\n");
      out.write("        		    type: \"hidden\",\n");
      out.write("        		    name: \"cpage\",\n");
      out.write("        		    value: \"1\"\n");
      out.write("              }));\n");
      out.write("        	  \n");
      out.write("              form.appendTo(\"body\").submit();\n");
      out.write("          }else if(p1content == \"상품등록\"){\n");
      out.write("        	  var form = $(\"<form>\", {\n");
      out.write("                  action: \"manager-regist.do\", // 서블릿의 URL\n");
      out.write("                  method: \"get\",\n");
      out.write("                  style: \"display: none;\" // 폼을 안보이도록 스타일링\n");
      out.write("              });\n");
      out.write("              form.appendTo(\"body\").submit();\n");
      out.write("          }else if(p1content == \"상품조회\"){\n");
      out.write("        	  var form = $(\"<form>\", {\n");
      out.write("                  action: \"manager-search.do\", // 서블릿의 URL\n");
      out.write("                  method: \"get\",\n");
      out.write("                  style: \"display: none;\" // 폼을 안보이도록 스타일링\n");
      out.write("              });\n");
      out.write("        	  \n");
      out.write("        	  form.append($(\"<input>\", {\n");
      out.write("      		    type: \"hidden\",\n");
      out.write("      		    name: \"cpage\",\n");
      out.write("      		    value: \"1\"\n");
      out.write("            }));\n");
      out.write("        	  \n");
      out.write("              form.appendTo(\"body\").submit();\n");
      out.write("          }else if(p1content == \"판매통계\"){\n");
      out.write("        	  var form = $(\"<form>\", {\n");
      out.write("                  action: \"manager-sales.do\", // 서블릿의 URL\n");
      out.write("                  method: \"get\",\n");
      out.write("                  style: \"display: none;\" // 폼을 안보이도록 스타일링\n");
      out.write("              });\n");
      out.write("              form.appendTo(\"body\").submit();\n");
      out.write("          }else if(p1content == \"이용자 통계\"){\n");
      out.write("        	  var form = $(\"<form>\", {\n");
      out.write("                  action: \"manager-user.do\", // 서블릿의 URL\n");
      out.write("                  method: \"get\",\n");
      out.write("                  style: \"display: none;\" // 폼을 안보이도록 스타일링\n");
      out.write("              });\n");
      out.write("              form.appendTo(\"body\").submit();\n");
      out.write("          }else if(p1content == \"카테고리 통계\"){\n");
      out.write("        	  var form = $(\"<form>\", {\n");
      out.write("                  action: \"manager-category.do\", // 서블릿의 URL\n");
      out.write("                  method: \"get\",\n");
      out.write("                  style: \"display: none;\" // 폼을 안보이도록 스타일링\n");
      out.write("              });\n");
      out.write("              form.appendTo(\"body\").submit();\n");
      out.write("          }\n");
      out.write("          \n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("  </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
