/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-21 10:44:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userNewUserFormView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

	String contextPath = request.getContextPath();
    String alertMsg =(String)session.getAttribute("alertMsg");

      out.write("\n");
      out.write("<!--  회원가입 화면 -->\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>티켓딱대 회원가입</title>\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\n");
      out.write("    <style>\n");
      out.write("        .logo_div{\n");
      out.write("            /* border: 1px solid; */\n");
      out.write("            width: 500px;\n");
      out.write("            height: 100px;\n");
      out.write("            margin: auto;\n");
      out.write("        }\n");
      out.write("        #logo{width: 95px;height: 40px;\n");
      out.write("               margin-top: 30px;}\n");
      out.write("        .outer{\n");
      out.write("            /* border: 1px solid; */\n");
      out.write("            width: 674px;\n");
      out.write("            height: 860px;\n");
      out.write("            margin: auto;\n");
      out.write("            margin-top: 35px;\n");
      out.write("        }\n");
      out.write("        .id_pwd_input{\n");
      out.write("            width: 100%;\n");
      out.write("            height: 150px;\n");
      out.write("            border: 1px solid rgba(128, 128, 128, 0.603);\n");
      out.write("            border-radius: 10px;\n");
      out.write("        }\n");
      out.write("        .id_pwd_input>div{\n");
      out.write("            width: 100%;\n");
      out.write("            height: 50px;\n");
      out.write("        }\n");
      out.write("        .line{\n");
      out.write("            border-top: 1px solid rgba(128, 128, 128, 0.603);\n");
      out.write("            border-bottom: 1px solid rgba(128, 128, 128, 0.603);\n");
      out.write("        }\n");
      out.write("        #newMember_img{width: 20px;height: 20px; margin-top: 15px; margin-left: 13px; float: left;}\n");
      out.write("        #new_user{border: none; height: 19px;  width: 342px; margin-top: 16px; margin-left: 5px; font-size: 18px; font-weight: 400; outline: none;}\n");
      out.write("        #new_user_pwd{border: none; height: 19px;  width: 342px; margin-top: 16px; margin-left: 5px; font-size: 18px; font-weight: 400; outline: none;}\n");
      out.write("        .message{\n");
      out.write("            width: 100%;\n");
      out.write("            height: 30px;\n");
      out.write("            /* border: 1px solid; */\n");
      out.write("        }\n");
      out.write("        .message_output{\n");
      out.write("            /* border: 1px solid; */\n");
      out.write("            /* width: 100%; */\n");
      out.write("            /* height: 60%; */\n");
      out.write("            line-height: 30px;\n");
      out.write("            color: red;\n");
      out.write("            font-weight: 900;\n");
      out.write("            font-size: 16px;\n");
      out.write("            margin: 0;\n");
      out.write("            \n");
      out.write("        }\n");
      out.write("        .info_input{\n");
      out.write("            width: 100%;\n");
      out.write("            height: 340px;\n");
      out.write("            border: 1px solid rgba(128, 128, 128, 0.603);\n");
      out.write("            border-radius: 10px;\n");
      out.write("        }\n");
      out.write("        .info_input>div{\n");
      out.write("            width: 100%;\n");
      out.write("            height: 50px;\n");
      out.write("        }\n");
      out.write("        .interest{color: rgba(66, 66, 66, 0.973); font-weight: 700; margin-top: 15px; margin-left: 15px;}\n");
      out.write("        .interest_box{width: 100%;  line-height: 0px;\n");
      out.write("            border-top: 2px solid rgba(87, 87, 87, 0.781);\n");
      out.write("            border-bottom: 1px solid rgba(128, 128, 128, 0.603);\n");
      out.write("         }\n");
      out.write("         .tag{line-height: 50px; margin-left: 40px; font-weight: 600; color: rgba(66, 66, 66, 0.973); }\n");
      out.write("         .choice_box{\n");
      out.write("            /* border-top:  1px solid rgba(128, 128, 128, 0.603); */\n");
      out.write("            /* border-bottom: 1px solid rgba(128, 128, 128, 0.603); */\n");
      out.write("            /* border-left: 1px solid rgba(128, 128, 128, 0.603); */\n");
      out.write("            width: 120px;\n");
      out.write("            height: 35px;\n");
      out.write("            margin-top: 7px ;\n");
      out.write("            border-radius: 2px;\n");
      out.write("         }\n");
      out.write("\n");
      out.write("\n");
      out.write("         #int{\n");
      out.write("            height: 50px;}\n");
      out.write("         #int>div{\n");
      out.write("            float: left;\n");
      out.write("         }\n");
      out.write("         #fst{\n");
      out.write("            margin-left: 40px;\n");
      out.write("            border-top-left-radius: 5px;\n");
      out.write("            border-bottom-left-radius: 5px;\n");
      out.write("            \n");
      out.write("         }\n");
      out.write("         #last{\n");
      out.write("            /* border-right:  1px solid rgba(128, 128, 128, 0.603); */\n");
      out.write("            border-top-right-radius: 5px;\n");
      out.write("            border-bottom-right-radius: 5px;\n");
      out.write("         }\n");
      out.write("        .int_btn_movie{\n");
      out.write("            width: 100%;height: 100%;\n");
      out.write("            background-color: white;\n");
      out.write("            border: 1px solid rgba(128, 128, 128, 0.603);\n");
      out.write("            border-radius: 5px;\n");
      out.write("        }\n");
      out.write("        .int_btn_display{\n");
      out.write("            width: 100%;height: 100%;\n");
      out.write("            background-color: white;\n");
      out.write("            border: 1px solid rgba(128, 128, 128, 0.603);\n");
      out.write("            border-radius: 5px;\n");
      out.write("        }\n");
      out.write("        .int_btn_show{\n");
      out.write("            width: 100%;height: 100%;\n");
      out.write("            background-color: white;\n");
      out.write("            border: 1px solid rgba(128, 128, 128, 0.603);\n");
      out.write("            border-radius: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("\n");
      out.write("        .active {\n");
      out.write("            border-color: red; /* 빨간색 테두리 */\n");
      out.write("        }\n");
      out.write("        button:hover{\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        .submit_box{\n");
      out.write("            /* border: 1px solid rebeccapurple; */\n");
      out.write("            border-radius: 5px;\n");
      out.write("            background-color: red;\n");
      out.write("            color: white;\n");
      out.write("            width: 460px;\n");
      out.write("            height: 50px;\n");
      out.write("            margin: auto;\n");
      out.write("            margin-top: 100px;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("        .submit_btn{\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            background-color: red;\n");
      out.write("            color: white;\n");
      out.write("            font-weight: 900;\n");
      out.write("            font-size: 20px;\n");
      out.write("            border: none;\n");
      out.write("            \n");
      out.write("        }\n");
      out.write("        .id_input{\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            border-top-left-radius: 10px;\n");
      out.write("            border-top-right-radius: 10px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
 if(alertMsg != null) { 
      out.write(" \n");
      out.write("		\n");
      out.write("		<script>\n");
      out.write("			alert(\"");
      out.print( alertMsg );
      out.write("\");\n");
      out.write("		</script>\n");
      out.write("		");
 session.removeAttribute("alertMsg"); 
      out.write("\n");
      out.write("		\n");
      out.write("	");
 } 
      out.write("\n");
      out.write("    <div class=\"logo_div\">\n");
      out.write("        <a href=\"");
      out.print(contextPath );
      out.write("\"><img src=\"resource/logo/logo.png\" id=\"logo\" alt=\"\"></a>\n");
      out.write("    </div>\n");
      out.write("    <form action=\"");
      out.print(contextPath );
      out.write("/insert.ur\" method=\"post\">\n");
      out.write("        <div class=\"outer\">\n");
      out.write("            <div class=\"id_pwd_input\">\n");
      out.write("                <div class=\"id_input\">\n");
      out.write("                    <img src=\"resource/이미지자료/로그인.png\" id=\"newMember_img\">\n");
      out.write("                        <input type=\"text\" id=\"new_user\" class=\"new_userId\" name=\"new_userId\" placeholder=\"아이디\" required>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"line\">\n");
      out.write("                    <img src=\"resource/이미지자료/비밀번호.png\" id=\"newMember_img\">\n");
      out.write("                        <input type=\"password\" id=\"new_user\" class=\"new_userPwd\" name=\"new_userPwd\" placeholder=\"비밀번호\" required>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"email_input\">\n");
      out.write("                    <img src=\"resource/이미지자료/이메일2.png\" id=\"newMember_img\">\n");
      out.write("                    <input type=\"email\" id=\"new_user\" name=\"new_userEmail\" placeholder=\"[선택] 이메일\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"message\">\n");
      out.write("                    <p class=\"message_output\"></p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"info_input\">\n");
      out.write("                <div class=\"name_input\">\n");
      out.write("                    <img src=\"resource/이미지자료/로그인.png\" id=\"newMember_img\">\n");
      out.write("                        <input type=\"text\" id=\"new_user\" class=\"new_user_name\" name=\"new_userName\" placeholder=\"이름\" required>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"line\">\n");
      out.write("                    <img src=\"resource/이미지자료/달력3.PNG\" id=\"newMember_img\">\n");
      out.write("                        <input type=\"text\" id=\"new_user_pwd\" name=\"new_userBday\" placeholder=\"생년월일 8자리 [ex)230824]\" required>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"phone_input\">\n");
      out.write("                    <img src=\"resource/이미지자료/phone.jpg\" id=\"newMember_img\">\n");
      out.write("                        <input type=\"text\" id=\"new_user\" class=\"new_user_phone\" name=\"new_userPhone\" placeholder=\"휴대폰 번호 [010-1234-5678]\" required>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"interest_box\" style=\"height: 30px;\">\n");
      out.write("                    <p class=\"interest\">[필수] 관심 카테고리</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"int_box\" >\n");
      out.write("                    <div class=\"int_movie\" id=\"int\">\n");
      out.write("                        <div class=\"tag\">영화</div>\n");
      out.write("                        <div class=\"choice_box\" id=\"fst\"><button type=\"button\" class=\"int_btn_movie\" id=\"movie\" onclick=\"selectMovie('1');\">로맨스</button></div>\n");
      out.write("                        <div class=\"choice_box\"><button type=\"button\" class=\"int_btn_movie\" id=\"movie\" onclick=\"selectMovie('2');\">공포/스릴러</button></div>\n");
      out.write("                        <div class=\"choice_box\"><button type=\"button\" class=\"int_btn_movie\" id=\"movie\" onclick=\"selectMovie('3');\">코미디</button></div>\n");
      out.write("                        <div class=\"choice_box\" id=\"last\"><button type=\"button\" class=\"int_btn_movie\" id=\"movie\" onclick=\"selectMovie('4');\">액션</button></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"line\" id=\"int\">\n");
      out.write("                        <div class=\"tag\">전시</div>\n");
      out.write("                        <div class=\"choice_box\" id=\"fst\"><button type=\"button\" class=\"int_btn_display\" id=\"paint\" onclick=\"selectDisplay('5');\">그림전시</button></div>\n");
      out.write("                        <div class=\"choice_box\"><button type=\"button\" class=\"int_btn_display\" id=\"composition\" onclick=\"selectDisplay('6');\">작품전시</button></div>\n");
      out.write("                        <div class=\"choice_box\"><button type=\"button\" class=\"int_btn_display\" id=\"photo\" onclick=\"selectDisplay('7');\">사진전시</button></div>\n");
      out.write("                        <div class=\"choice_box\" id=\"last\"><button type=\"button\" class=\"int_btn_display\" id=\"experience\" onclick=\"selectDisplay('8');\">체험전시</button></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"int_movie\" id=\"int\">\n");
      out.write("                        <div class=\"tag\">공연</div>\n");
      out.write("                        <div class=\"choice_box\" id=\"fst\"><button type=\"button\" class=\"int_btn_show\" id=\"musical\" onclick=\"selectShow('9');\" >뮤지컬</button></div>\n");
      out.write("                        <div class=\"choice_box\"><button type=\"button\" class=\"int_btn_show\" id=\"act\" onclick=\"selectShow('10');\" >연극</button></div>\n");
      out.write("                        <div class=\"choice_box\"><button type=\"button\" class=\"int_btn_show\" id=\"classical\" onclick=\"selectShow('11');\" >클래식</button></div>\n");
      out.write("                        <div class=\"choice_box\" id=\"last\"><button type=\"button\" class=\"int_btn_show\" id=\"concert\" onclick=\"selectShow('12');\" >콘서트</button></div>\n");
      out.write("                    </div> \n");
      out.write("                    <input type=\"hidden\" name=\"select_movie_hidden\" id=\"select_movie_hidden\">\n");
      out.write("                    <input type=\"hidden\" name=\"select_display_hidden\" id=\"select_display_hidden\">\n");
      out.write("                    <input type=\"hidden\" name=\"select_show_hidden\" id=\"select_show_hidden\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"submit_box\">\n");
      out.write("                <button class=\"submit_btn\" type=\"submit\" onclick=\"test4();\">회원 가입</button>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("           \n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        function selectMovie(value){\n");
      out.write("            $(\"#select_movie_hidden\").attr(\"value\", value);\n");
      out.write("        }\n");
      out.write("        function selectDisplay(value){\n");
      out.write("            $(\"#select_display_hidden\").attr(\"value\", value);\n");
      out.write("        }\n");
      out.write("        function selectShow(value){\n");
      out.write("            $(\"#select_show_hidden\").attr(\"value\", value);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        $(document).ready(function() {\n");
      out.write("\n");
      out.write("            $(\".int_btn_movie\").click(function() {\n");
      out.write("                // 모든 버튼의 테두리 색상을 원래대로 되돌립니다.\n");
      out.write("                $(\".int_btn_movie\").css(\"border-color\", \"rgba(128, 128, 128, 0.603)\");\n");
      out.write("                $(\".int_btn_movie\").css(\"color\", \"gray\");\n");
      out.write("                // 클릭한 버튼의 테두리 색상을 빨간색으로 변경합니다.\n");
      out.write("                $(this).css(\"border-color\", \"red\");\n");
      out.write("                $(this).css(\"color\", \"red\");\n");
      out.write("            });\n");
      out.write("            $(\".int_btn_display\").click(function() {\n");
      out.write("                // 모든 버튼의 테두리 색상을 원래대로 되돌립니다.\n");
      out.write("                $(\".int_btn_display\").css(\"border-color\", \"rgba(128, 128, 128, 0.603)\");\n");
      out.write("                $(\".int_btn_display\").css(\"color\", \"gray\");\n");
      out.write("                // 클릭한 버튼의 테두리 색상을 빨간색으로 변경합니다.\n");
      out.write("                $(this).css(\"border-color\", \"red\");\n");
      out.write("                $(this).css(\"color\", \"red\");\n");
      out.write("            });\n");
      out.write("              $(\".int_btn_show\").click(function() {\n");
      out.write("                // 모든 버튼의 테두리 색상을 원래대로 되돌립니다.\n");
      out.write("                $(\".int_btn_show\").css(\"border-color\", \"rgba(128, 128, 128, 0.603)\");\n");
      out.write("                $(\".int_btn_show\").css(\"color\", \"gray\");\n");
      out.write("                // 클릭한 버튼의 테두리 색상을 빨간색으로 변경합니다.\n");
      out.write("                $(this).css(\"border-color\", \"red\");\n");
      out.write("                $(this).css(\"color\", \"red\");\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("     <script>\n");
      out.write("        function test4() {\n");
      out.write("            // 사용자가 입력한 생년월일 값\n");
      out.write("            const value = document.getElementById(\"new_user_pwd\").value;\n");
      out.write("           \n");
      out.write("            var phone = $(\".new_user_phone\").val();\n");
      out.write("\n");
      out.write("            var regPhone= /^01([0|1|6|7|8|9])-?([0-9]{3,4})-?([0-9]{4})$/;\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            let regExp = /^\\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])$/;\n");
      out.write("\n");
      out.write("            var idReg = /^[a-z]+[a-z0-9]{5,19}$/g;\n");
      out.write("\n");
      out.write("            let PwdReg = /^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,15}$/\n");
      out.write("            \n");
      out.write("            var nameReg = /^[a-zA-Z가-힣]{2,15}$/\n");
      out.write("\n");
      out.write("            if($(\".submit_btn\").attr(\"type\") == \"button\" ){\n");
      out.write("                alert(\"아이디를 확인해주세요.\");\n");
      out.write("            }else{\n");
      out.write("\n");
      out.write("                if( !idReg.test( $(\".new_userId\").val() ) ) { // 아이디 안맞다\n");
      out.write("                    $(\".submit_btn\").attr(\"type\",\"button\"); \n");
      out.write("                    alert(\"아이디는 영문자로 시작하는 6~20자 영문자 또는 숫자이어야 합니다.\");\n");
      out.write("                    $(\".message_output\").text(\"* 입력하신 아이디가 잘못되었습니다.\");\n");
      out.write("                    \n");
      out.write("                }else{ // 아이디 맞다 \n");
      out.write("                    $(\".message_output\").text(\" \");\n");
      out.write("\n");
      out.write("                    if(!PwdReg.test( $(\".new_userPwd\").val() )){ // 비번 틀리다\n");
      out.write("                        $(\".submit_btn\").attr(\"type\",\"button\"); \n");
      out.write("                        alert(\"비밀번호는 영문 숫자 특수기호 조합 8자리 이상이어야 합니다.\")\n");
      out.write("                        $(\".message_output\").text(\"* 입력하신 비밀번호가 잘못되었습니다.\");\n");
      out.write("                    }else { // 비번맞다\n");
      out.write("\n");
      out.write("                        if(!nameReg.test($(\".new_user_name\").val() )){ // 이름 틀리다\n");
      out.write("                            $(\".submit_btn\").attr(\"type\",\"button\"); \n");
      out.write("                            alert(\"이름은 영어나 한글로 2~15자 이어야 합니다.\")\n");
      out.write("                            $(\".message_output\").text(\"* 입력하신 이름이 잘못되었습니다.\");\n");
      out.write("                        \n");
      out.write("                        }else{ // 이름맞다\n");
      out.write("                            \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                            if(regExp.test(value)){ // 생년월일 맞다\n");
      out.write("                                $(\".message_output\").text(\" \");\n");
      out.write("\n");
      out.write("                                if (regPhone.test(phone) == true) { // 전번 체크 함\n");
      out.write("\n");
      out.write("                                    if($(\"#select_movie_hidden\").val() == \"\" ){ // 영화 안함\n");
      out.write("                                        $(\".submit_btn\").attr(\"type\",\"button\"); \n");
      out.write("                                        alert(\"관심 카테고리 (영화)를 선택해 주세요.\")\n");
      out.write("                                        $(\".message_output\").text(\"* 관심 카테고리 (영화)를 선택해 주세요.\");\n");
      out.write("\n");
      out.write("                                    }else{ // 영화 체크함\n");
      out.write("\n");
      out.write("                                        if($(\"#select_display_hidden\").val() == \"\" ){ // 전시 체크 암함\n");
      out.write("                                            $(\".submit_btn\").attr(\"type\",\"button\"); \n");
      out.write("                                            alert(\"관심 카테고리 (전시)를 선택해 주세요.\")\n");
      out.write("                                            $(\".message_output\").text(\"* 관심 카테고리 (전시)를 선택해 주세요.\");\n");
      out.write("                                        }else{ // 전시 체크함\n");
      out.write("\n");
      out.write("                                            if($(\"#select_show_hidden\").val() == \"\" ){ // 공연 체크 안함\n");
      out.write("                                                $(\".submit_btn\").attr(\"type\",\"button\"); \n");
      out.write("                                                alert(\"관심 카테고리 (공연)를 선택해 주세요.\")\n");
      out.write("                                                $(\".message_output\").text(\"* 관심 카테고리 (공연)를 선택해 주세요.\");\n");
      out.write("                                            }else{ // 공연 체크함\n");
      out.write("                                                $(\".submit_btn\").attr(\"type\",\"submit\"); \n");
      out.write("\n");
      out.write("                                            \n");
      out.write("                                            }\n");
      out.write("                                        }\n");
      out.write("                                    }\n");
      out.write("                                }else {// 전번 체크 안함\n");
      out.write("                                    $(\".submit_btn\").attr(\"type\",\"button\"); \n");
      out.write("                                    alert(\"휴대폰 번호를 확인해주세요.\")\n");
      out.write("                                    $(\".message_output\").text(\"* 입력하신 전화번호가 잘못되었습니다.\");\n");
      out.write("                                }\n");
      out.write("                                \n");
      out.write("                            }else {  // 생년월일 틀림\n");
      out.write("                                alert(\"생년월일이 잘못되었습니다.\")\n");
      out.write("                                $(\".submit_btn\").attr(\"type\",\"button\"); \n");
      out.write("                                $(\".message_output\").text(\"* 입력하신 생년월일이 잘못되었습니다.\");\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                }\n");
      out.write("\n");
      out.write("            }   \n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    <script>\n");
      out.write("    var idReg = /^[a-z]+[a-z0-9]{5,19}$/;\n");
      out.write("\n");
      out.write("    var $newUserId = $(\".new_userId\");\n");
      out.write("    var $idInput = $(\".id_input\");\n");
      out.write("    var $messageOutput = $(\".message_output\");\n");
      out.write("    var $submitBtn = $(\".submit_btn\");\n");
      out.write("\n");
      out.write("    $newUserId.keyup(function() {\n");
      out.write("        var userId = $newUserId.val();\n");
      out.write("        \n");
      out.write("        if (!idReg.test(userId)) { // 아이디 체크 불합격\n");
      out.write("            $idInput.css(\"border\", \"2px solid red\");\n");
      out.write("            $messageOutput.text(\"* 아이디는 영문자로 시작하는 6~20자 영문자 또는 숫자이어야 합니다.\");\n");
      out.write("            $submitBtn.attr(\"type\", \"button\");\n");
      out.write("        } else { // 합격\n");
      out.write("            $idInput.css(\"border\", \"none\");\n");
      out.write("            $messageOutput.text(\"\");\n");
      out.write("\n");
      out.write("            $.ajax({\n");
      out.write("                url: \"idCheck.ur\",\n");
      out.write("                data: { checkId: userId },\n");
      out.write("                success: function(result) {\n");
      out.write("                    console.log(result);\n");
      out.write("                    if (result === \"NNNNY\") { // 사용가능\n");
      out.write("                        $idInput.css(\"border\", \"none\");\n");
      out.write("                        $messageOutput.text(\"* 사용 가능한 아이디 입니다.\");\n");
      out.write("                        $submitBtn.attr(\"type\", \"submit\");\n");
      out.write("                    } else if (result === \"NNNNN\") { // 사용불가능\n");
      out.write("                        $idInput.css(\"border\", \"2px solid red\");\n");
      out.write("                        console.log($submitBtn.attr(\"type\"));\n");
      out.write("                        $submitBtn.attr(\"type\", \"button\");\n");
      out.write("                        $messageOutput.text(\"* 이미 존재하거나 탈퇴한 회원의 아이디입니다.\");\n");
      out.write("                    } else {\n");
      out.write("                        console.log(result);\n");
      out.write("                        alert(\"오류발생\");\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                error: function() {\n");
      out.write("                    console.log(\"아이디 중복체크 통신 실패!\");\n");
      out.write("                    alert(\"아이디 중복체크 통신 실패!\");\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
